apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portfolio
  annotations:
    github.com/project-slug: jamiejacob/portfolio
spec:
  type: other
  lifecycle: unknown
  owner: guests
